import type { Metadata } from "next";
import GlassPane from "@/components/glass-pane";
import "./globals.css";
import { Toaster } from "sonner";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`antialiased`}>
        <main className="h-screen w-screen p-1 md:p-6 rainbow-mesh">
          <GlassPane className="-z-10 h-full w-full flex justify-center items-center ">
            {children}
            <Toaster />
          </GlassPane>
        </main>
      </body>
    </html>
  );
}
