import type { Metadata } from "next";
import localFont from "next/font/local";
import GlassPane from "@/components/glass-pane";
import "./globals.css";

const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="h-screen w-screen p-6 rainbow-mesh bg-red-700">
          <GlassPane className="h-full w-full flex justify-center items-center">
            {children}
          </GlassPane>
        </main>
      </body>
    </html>
  );
}
